<?php

$payers = array("Vipul Naik", "Peter Hurford", "Alex Flint");

$yearList = array("2015", "2016", "2017", "2018", "2019");

$monthList = array("2015-01","2015-02","2015-03","2015-04","2015-05","2015-06","2015-07","2015-08","2015-09","2015-10","2015-11","2015-12","2016-01","2016-02","2016-03","2016-04","2016-05","2016-06","2016-07","2016-08","2016-09","2016-10","2016-11","2016-12","2017-01", "2017-02", "2017-03", "2017-04", "2017-05", "2017-06", "2017-07", "2017-08", "2017-09", "2017-10", "2017-11", "2017-12", "2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06", "2018-07", "2018-08", "2018-09", "2018-10", "2018-11", "2018-12", "2019-01", "2019-02", "2019-03", "2019-04");

$taskTypes = array('Wikipedia page creation','Wikipedia page update','Wikipedia page translation','Attempted Wikipedia work','Miscellaneous Wikipedia work','Preliminary research','Blog post or article','Survey creation','Survey recruitment','Coding','Consulting','Review','Wiki page creation','Wiki page update','Questions and answers','Contacting people','Data entry','Task listing','Content migration','Timelines page creation','Timelines page update','Worker onboarding and assistance','On-the-ground investigation','People watching');

$taskVenues = array('Wikipedia','Wikipedia Views','Effective Altruism Forum','LessWrong','Personal website','Wikimedia meta','wikiHow','Quora','Market subwiki','Donations list website', 'Contract work for Vipul Naik','Timelines wiki','PredictionBook','Facebook', 'Devec subwiki', 'Demography subwiki', 'Devec/Demography data portal','AI Watch','People repo','Wikipedia spotlight','Computing data project','Cause Prioritization Wiki','Org Watch','None');

$taskFormats = array('Timeline','Prose','Table','Code','Photos/videos + notes','Code and data','Communication with Vipul','Communication with worker','Email');

$topics = array('Health','Global health','Country healthcare','Animal welfare','Technology','Philanthropy','People','Wikipedia','United States taxation','United States migration','United States politics','Political philosophy','Digital preservation','Artificial intelligence','Poverty','Government','GiveWell');

$paymentMethods = array("Cash","Check","PayPal","Wire transfer","Western Union","Debit card via Facebook","Venmo","Ethereum");

?>